export enum WalletStatus {
  NOT_ENOUGH_FUND = 'NOT_ENOUGH_FUND',
  NOT_ENOUGH_GAS = 'NOT_ENOUGH_GAS',
  OK='OK',
  INVALID = ' INVALID',
  SUCCESS = 'SUCCESS',
  FAIL = 'FAIL',
  NOT_FOUND = 'NOT_FOUND',
  FOUND = 'FOUND',
  SELF = 'SELF',
}
