export enum Action {
  DEPOSIT = 'Deposit',
  WITHDRAW = 'Withdraw',
  TRANSACTION = 'Transaction',
  INFORMATION = 'Information',
  CREATE = 'Create',
  TRANSFER = 'Transfer',
  TRANSFER_BY_ADDRESS = 'Transfer by address',
  TRANFER_BY_PUBLIC_KEY = 'transfer by publickey',
  CANCEL = 'Cancel',
  HISTORY = 'History',
  SEND_MONEY_ADDRESS = 'Send money by adress',
  SEND_MONEY_PUBLIC_KEY = 'sendMoneyPublicKey',
  NOTTHING = '',
}
