export enum Button {
  DEPOSIT = 'deposit',
  WITHDRAW = 'withdraw',
  TRANSACTION = 'transaction',
  INFORMATION = 'information',
  CREATE = 'create',
  TRANSFER = 'transfer',
  CANCEL = 'cancel',
  WALLET_ADDRESS = 'addressTransfer',
  PUBLICKEY = 'publickey',
  HISTORY = 'history',
  SEARCH = 'search',
  TEST = 'test',
  HUSD = "HUSD",
  MTK = "MTK",
  DELETE = "DELETE",
  IMPORT = "IMPORT",
  REPLACE_WALLET = "REPLACE_WALLET",
  PK = "PK"
}
